### ISSUE TITLE
Can not upload dataset

### ISSUE THREAD

**Issue by xuezhongyuan** [gangtao/dataplay3#9]
Hi,Why am I can't upload dataset when I finished install？

**Comment by gangtao** [comment]
when you upload dataset, you need click the `upload` button at the last step, this is a usability issue, which I would like to improve in the future, try if this solve your problem.

**Comment by xuezhongyuan** [comment]
Thank you man,but when I try again,It returns "请求错误 500: http://localhost:8000/api/datasets" 
403,sorry you don't access to this page.

**Comment by yepengxj** [comment]
Can't upload dataset 

[ERROR] faile to create dataset
Traceback (most recent call last):
  File "/home/dataplay3/server/dataplay/datasvc/service.py", line 48, in create_datasets
    DatasetManager.add_dataset(request_body)
  File "/home/dataplay3/server/dataplay/datasvc/manager.py", line 61, in add_dataset
    ConfigurationManager.add_section(domain, section, value)
  File "/home/dataplay3/server/dataplay/confsvc/manager.py", line 70, in add_section
    cfg.set(section, option, value[option])
  File "/usr/lib/python3.6/configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
ERROR:sanic.root:faile to create dataset
Traceback (most recent call last):
  File "/home/dataplay3/server/dataplay/datasvc/service.py", line 48, in create_datasets
    DatasetManager.add_dataset(request_body)
  File "/home/dataplay3/server/dataplay/datasvc/manager.py", line 61, in add_dataset
    ConfigurationManager.add_section(domain, section, value)
  File "/home/dataplay3/server/dataplay/confsvc/manager.py", line 70, in add_section
    cfg.set(section, option, value[option])
  File "/usr/lib/python3.6/configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

**Comment by yiming-lzx** [comment]
你好，点击click botton to create the dataset, 报错：file type: application/vnd.ms-excel is not supported, 由于我不是前端开发者，对这个报错无从下手，希望能得到指点，我做了几方面尝试：
1、在旧版本的dataplay里，是可以上传csv数据集的，但是来到dataplay3就不行；
2、csv文件加了“”号，有header，最后一行也没空；
3、操作顺序是按照视频来的；
